src/Entity/Adoption.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use App\Entity\Traits\HasIdTrait;
use App\Entity\Traits\HasNameTrait;
use App\Repository\AdoptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=AdoptionRepository::class)
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     attributes={
 *         "order"={"updatedAt": "DESC"}
 *     },
 *     paginationItemsPerPage=1
 * )
 * @ApiFilter(SearchFilter::class, properties={"dogs.id": "exact", "dogs.name": "partial"})
 */
class Adoption
{
    use HasIdTrait;
    use HasNameTrait;
    use TimestampableEntity;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="adoption")
     * @ApiSubresource(
     *     maxDepth=2
     * )
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Dog::class, mappedBy="adoption", cascade={"persist"})
     * @ApiSubresource(
     *     maxDepth=2
     * )
     */
    private $dogs;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="adoptions")
     * @ApiSubresource(
     *     maxDepth=2
     * )
     */
    private $user;


    public function __construct()
    {
        $this->contacts = new ArrayCollection();
        $this->dogs = new ArrayCollection();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
            $contact->setAdoption($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getAdoption() === $this) {
                $contact->setAdoption(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Dog[]
     */
    public function getDogs(): Collection
    {
        return $this->dogs;
    }

    public function addDog(Dog $dog): self
    {
        if (!$this->dogs->contains($dog)) {
            $this->dogs[] = $dog;
            $dog->setAdoption($this);
        }

        return $this;
    }

    public function removeDog(Dog $dog): self
    {
        if ($this->dogs->removeElement($dog)) {
            // set the owning side to null (unless already changed)
            if ($dog->getAdoption() === $this) {
                $dog->setAdoption(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        $string = $this->getName();

        if (!empty($this->getDogs())) {
            $string .= ' (';
            foreach ($this->getDogs() as $key => $dog) {
                $string .= $dog->getName();
                if ($key < count($this->getDogs()) - 1) {
                    $string .= ', ';
                }
            }
            $string .= ')';
        }

        return $string;
    }

    public function isClosed(): bool
    {
        foreach ($this->getDogs() as $dog) {
            if (!$dog->getTaken()) {
                return false;
            }
        }

        return true;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Dog.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Entity\Traits\HasIdTrait;
use App\Entity\Traits\HasNameTrait;
use App\Repository\DogRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=DogRepository::class)
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"}
 * )
 */
class Dog
{
    use HasIdTrait;
    use HasNameTrait;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Adoption::class, inversedBy="dogs", cascade={"persist"})
     */
    private $adoption;

    /**
     * @ORM\ManyToMany(targetEntity=Breed::class, mappedBy="dogs")
     */
    private $breeds;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="dog", cascade={"persist"})
     * @Groups({"read"})
     */
    private $images;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"read"})
     */
    private $taken;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="dogs")
     */
    private $user;

    public function __construct()
    {
        $this->breeds = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->taken = false;
    }

    public function getBirthDate(): ?DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAdoption(): ?Adoption
    {
        return $this->adoption;
    }

    public function setAdoption(?Adoption $adoption): self
    {
        $this->adoption = $adoption;

        return $this;
    }

    /**
     * @return Collection|Breed[]
     */
    public function getBreeds(): Collection
    {
        return $this->breeds;
    }

    public function addBreed(Breed $breed): self
    {
        if (!$this->breeds->contains($breed)) {
            $this->breeds[] = $breed;
            $breed->addDog($this);
        }

        return $this;
    }

    public function removeBreed(Breed $breed): self
    {
        if ($this->breeds->removeElement($breed)) {
            $breed->removeDog($this);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setDog($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getDog() === $this) {
                $image->setDog(null);
            }
        }

        return $this;
    }

    public function getAge(): ?int
    {
        if (empty($this->getBirthDate())) {
            return null;
        }

        $now = new DateTime();

        $diff = $this->getBirthDate()->diff($now, true);

        return $diff->y;
    }

    public function getTaken(): ?bool
    {
        return $this->taken;
    }

    public function setTaken(bool $taken): self
    {
        $this->taken = $taken;

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/AdoptionType.php
<?php

namespace App\Form;

use App\Entity\Adoption;
use App\Entity\Dog;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdoptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
            ])
            ->add('description', TextareaType::class, [
                'required' => true,
            ])
            ->add('dogs', EntityType::class, [
                'class'        => Dog::class,
                "multiple"     => true,
                'required'     => true,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adoption::class,
        ]);
    }
}

src/Controller/AdoptionController.php
<?php

namespace App\Controller;

use App\Entity\Adoption;
use App\Entity\User;
use App\Form\AdoptionType;
use App\Repository\AdoptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/annonces")
 */
class AdoptionController extends AbstractController
{
    /**
     * @Route("/", name="adoption_index")
     */
    public function index(AdoptionRepository $adoptionRepository): Response
    {
        $adoptions = $adoptionRepository->findNotTaken();

        return $this->render('adoption/index.html.twig', [
            'adoptions' => $adoptions,
        ]);
    }

    /**
     * @Route("/nouvelle", name="adoption_new")
     * @Route("/{id}/modifier", name="adoption_edit")
     * @IsGranted("ROLE_USER")
     */
    public function form(Request $request, EntityManagerInterface $em, ?Adoption $adoption = null): Response
    {
        if (empty($adoption)) {
            $adoption = new Adoption();
        }

        $form = $this->createForm(AdoptionType::class, $adoption);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var User $user */
            $user = $this->getUser();
            $adoption->setUser($user);
            $em->persist($adoption);
            $em->flush();

            return $this->redirectToRoute('adoption_index');
        }

        return $this->render('adoption/form.html.twig', [
            'adoption' => $adoption,
            'form'     => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="adoption_show")
     */
    public function show(Adoption $adoption): Response
    {
        if ($adoption->isClosed()) {
            $this->addFlash('danger', 'Cette annonce a été pourvue et tous ses chiens ont maintenant une famille !');

            return $this->redirectToRoute('adoption_index');
        }

        return $this->render('adoption/show.html.twig', [
            'adoption' => $adoption,
        ]);
    }
}

templates/adoption/_one-adoption.html.twig
<div class="col-md-4 col-sm-12">
    <div class="card">
        <h2 class="card-header">
            <a href="{{ path('adoption_show', {
                id: adoption.id,
            }) }}">
                {{ adoption.name }}
            </a>
        </h2>
        <div class="card-body">
            <p class="card-text">
                {{ adoption.description }}
            </p>
            {% for dog in adoption.dogs %}
                <h3>
                    {{ dog.name }}
                    {% if dog.birthDate %}
                        ({{ dog.age }} ans)
                    {% endif %}
                    {% if dog.taken %}
                        (adopté)
                    {% endif %}
                </h3>
                <div class="row">
                    {% for image in dog.images %}
                        {% if image.path starts with 'http' %}
                            <img src="{{ image.path }}" class="col-6" alt="" style="height: auto">
                        {% else %}
                            <img src="{{ vich_uploader_asset(image) }}" class="col-6" alt="" style="height: auto">
                        {% endif %}
                    {% endfor %}
                </div>
                <p>
                    {{ dog.description }}
                </p>
            {% endfor %}
        </div>
        <div class="card-footer text-muted">
            {{ adoption.updatedAt|date('d/m/Y à H:i') }}
        </div>
    </div>
</div>

templates/adoption/form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_row(form.name, {
            label: "Titre de l'annonce",
            row_attr: {
                class: 'mb-3',
            },
            label_attr: {
                class: 'form-label',
            },
            attr: {
                class: 'form-control',
            },
        }) }}
        {{ form_row(form.description, {
            label: "Détails de l'annonce",
            row_attr: {
                class: 'mb-3',
            },
            label_attr: {
                class: 'form-label',
            },
            attr: {
                class: 'form-control',
            },
        }) }}
        {{ form_row(form.dogs, {
            label: "Chiens associés à l'annonce",
            row_attr: {
                class: 'mb-3',
            },
            label_attr: {
                class: 'form-label',
            },
            attr: {
                class: 'form-control',
            },
        }) }}
        <button type="submit">Valider</button>
    {{ form_end(form) }}
{% endblock %}

{% block title %}
    Créer / modifier une annonce
{% endblock %}

templates/adoption/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Chiens à l'adoption
{% endblock %}

{% block body %}
    <h1>Chiens à l'adoption</h1>
    <div class="row g-4">
        {% for adoption in adoptions %}
            {% include 'adoption/_one-adoption.html.twig' with {
				adoption: adoption
			} only %}
        {% endfor %}
    </div>
{% endblock %}

templates/adoption/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ adoption.name }}
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>{{ adoption.name }}</h1>
        <p>
            {{ adoption.description }}
        </p>
        {% for dog in adoption.dogs %}
            <h3>
                {{ dog.name }}
                {% if dog.birthDate %}
                    ({{ dog.age }} ans)
                {% endif %}
                {% if dog.taken %}
                    (adopté)
                {% endif %}
            </h3>
            {% for image in dog.images %}
                <img src="{{ image.path }}" class="card-img-top" alt="">
            {% endfor %}
            <p>
                {{ dog.description }}
            </p>
        {% endfor %}
        <a href="{{ path('default_contact_for_adoption', { id: adoption.id }) }}">Nous contacter</a>
    </div>
{% endblock %}